-- Admin TOTP 2FA fields
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "twoFactorSecret" TEXT;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "twoFactorEnabledAt" TIMESTAMP(3);
