/**
 * Electricity Distribution Company (DISCO) Codes
 * Required for NIN and Address verification
 */
export enum DiscoCode {
  ABUJA = 'ABUJA',
  EKO = 'EKO',
  IKEJA = 'IKEJA',
  IBADAN = 'IBADAN',
  ENUGU = 'ENUGU',
  PH = 'PH',
  JOS = 'JOS',
  KADUNA = 'KADUNA',
  KANO = 'KANO',
  BH = 'BH',
  PROTOGY = 'PROTOGY',
  PHISBOND = 'PHISBOND',
  ACCESSPOWER = 'ACCESSPOWER',
  YOLA = 'YOLA',
  ABIA = 'ABIA',
  ADAMAWA = 'ADAMAWA',
  AKWA_IBOM = 'AKWA IBOM',
  ANAMBRA = 'ANAMBRA',
  BAUCHI = 'BAUCHI',
  BAYELSA = 'BAYELSA',
  BENUE = 'BENUE',
  BORNO = 'BORNO',
  CROSS_RIVER = 'CROSS RIVER',
  DELTA = 'DELTA',
  EBONYI = 'EBONYI',
  EDO = 'EDO',
  EKITI = 'EKITI',
  GOMBE = 'GOMBE',
  IMO = 'IMO',
  JIGAWA = 'JIGAWA',
  KATSINA = 'KATSINA',
  KEBBI = 'KEBBI',
  KOGI = 'KOGI',
  KWARA = 'KWARA',
  LAGOS = 'LAGOS',
  NASSARAWA = 'NASSARAWA',
  NIGER = 'NIGER',
  OGUN = 'OGUN',
  ONDO = 'ONDO',
  OSUN = 'OSUN',
  OYO = 'OYO',
  PLATEAU = 'PLATEAU',
  RIVERS = 'RIVERS',
  SOKOTO = 'SOKOTO',
  TARABA = 'TARABA',
  YOBE = 'YOBE',
  ZAMFARA = 'ZAMFARA',
  FCT = 'FCT',
}

