import { AdminRole } from '../../../generated/prisma/enums.js';

export const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'view_users',
  EDIT_USERS: 'edit_users',
  DELETE_USERS: 'delete_users',

  // Financial
  VIEW_TRANSACTIONS: 'view_transactions',
  PROCESS_REFUNDS: 'process_refunds',
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  MANAGE_FINANCIAL_SETTINGS: 'manage_financial_settings',

  // KYC
  VIEW_KYC_REQUESTS: 'view_kyc_requests',
  APPROVE_KYC: 'approve_kyc',
  REJECT_KYC: 'reject_kyc',
  RESTRICT_USERS: 'restrict_users',
  UNRESTRICT_USERS: 'unrestrict_users',
  SEND_KYC_REMINDERS: 'send_kyc_reminders',

  // System Config
  MANAGE_CONFIG: 'manage_config',
  VIEW_CONFIG: 'view_config',

  // Support
  VIEW_SUPPORT_TICKETS: 'view_support_tickets',
  RESPOND_TO_TICKETS: 'respond_to_tickets',

  // Admin Management
  MANAGE_ADMINS: 'manage_admins',
  VIEW_ADMINS: 'view_admins',

  // Events
  VIEW_EVENTS: 'view_events',
  MANAGE_EVENTS: 'manage_events',

  // Wallets
  VIEW_WALLETS: 'view_wallets',
  MANAGE_WALLETS: 'manage_wallets',
  ADJUST_INTERNAL_BALANCES: 'adjust_internal_balances',

  // AML Alerts
  VIEW_AML_ALERTS: 'view_aml_alerts',
  MANAGE_AML_ALERTS: 'manage_aml_alerts',

  // Audit Logs
  VIEW_AUDIT_LOGS: 'view_audit_logs',

  // Withdrawals
  VIEW_WITHDRAWALS: 'view_withdrawals',
  MANAGE_WITHDRAWALS: 'manage_withdrawals',

  // Notifications
  VIEW_NOTIFICATIONS: 'view_notifications',

  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  [AdminRole.SUPER_ADMIN]: [
    // All permissions
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.PROCESS_REFUNDS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_SETTINGS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.REJECT_KYC,
    PERMISSIONS.RESTRICT_USERS,
    PERMISSIONS.UNRESTRICT_USERS,
    PERMISSIONS.SEND_KYC_REMINDERS,
    PERMISSIONS.MANAGE_CONFIG,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.VIEW_ADMINS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.MANAGE_WALLETS,
    PERMISSIONS.ADJUST_INTERNAL_BALANCES,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.MANAGE_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.MANAGE_WITHDRAWALS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [AdminRole.FINANCE_ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.PROCESS_REFUNDS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_SETTINGS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.ADJUST_INTERNAL_BALANCES,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.MANAGE_WITHDRAWALS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [AdminRole.SUPPORT]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.SEND_KYC_REMINDERS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [AdminRole.COMPLIANCE]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.REJECT_KYC,
    PERMISSIONS.RESTRICT_USERS,
    PERMISSIONS.UNRESTRICT_USERS,
    PERMISSIONS.SEND_KYC_REMINDERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.MANAGE_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [AdminRole.OPERATIONS]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.MANAGE_CONFIG,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.MANAGE_WALLETS,
    PERMISSIONS.ADJUST_INTERNAL_BALANCES,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [AdminRole.VIEW_ONLY]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
};
