import { AdminRole } from '../../../generated/prisma/enums.js';

export const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'view_users',
  EDIT_USERS: 'edit_users',
  DELETE_USERS: 'delete_users',
  
  // Financial
  VIEW_TRANSACTIONS: 'view_transactions',
  PROCESS_REFUNDS: 'process_refunds',
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  MANAGE_FINANCIAL_SETTINGS: 'manage_financial_settings',
  
  // KYC
  VIEW_KYC_REQUESTS: 'view_kyc_requests',
  APPROVE_KYC: 'approve_kyc',
  REJECT_KYC: 'reject_kyc',
  APPROVE_UTILITY_BILL: 'approve_utility_bill',
  REJECT_UTILITY_BILL: 'reject_utility_bill',
  RESTRICT_USERS: 'restrict_users',
  UNRESTRICT_USERS: 'unrestrict_users',
  
  // System Config
  MANAGE_CONFIG: 'manage_config',
  VIEW_CONFIG: 'view_config',
  
  // Support
  VIEW_SUPPORT_TICKETS: 'view_support_tickets',
  RESPOND_TO_TICKETS: 'respond_to_tickets',
  
  // Admin Management
  MANAGE_ADMINS: 'manage_admins',
  VIEW_ADMINS: 'view_admins',
  
  // Events
  VIEW_EVENTS: 'view_events',
  MANAGE_EVENTS: 'manage_events',
  
  // Wallets
  VIEW_WALLETS: 'view_wallets',
  MANAGE_WALLETS: 'manage_wallets',
  
  // AML Alerts
  VIEW_AML_ALERTS: 'view_aml_alerts',
  MANAGE_AML_ALERTS: 'manage_aml_alerts',
  
  // Audit Logs
  VIEW_AUDIT_LOGS: 'view_audit_logs',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  [AdminRole.SUPER_ADMIN]: [
    // All permissions
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.PROCESS_REFUNDS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_SETTINGS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.REJECT_KYC,
    PERMISSIONS.APPROVE_UTILITY_BILL,
    PERMISSIONS.REJECT_UTILITY_BILL,
    PERMISSIONS.RESTRICT_USERS,
    PERMISSIONS.UNRESTRICT_USERS,
    PERMISSIONS.MANAGE_CONFIG,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.VIEW_ADMINS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.MANAGE_WALLETS,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.MANAGE_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [AdminRole.FINANCE_ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.PROCESS_REFUNDS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_SETTINGS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [AdminRole.SUPPORT]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_CONFIG,
  ],
  [AdminRole.COMPLIANCE]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.REJECT_KYC,
    PERMISSIONS.APPROVE_UTILITY_BILL,
    PERMISSIONS.REJECT_UTILITY_BILL,
    PERMISSIONS.RESTRICT_USERS,
    PERMISSIONS.UNRESTRICT_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.MANAGE_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [AdminRole.OPERATIONS]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.MANAGE_CONFIG,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.RESPOND_TO_TICKETS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.MANAGE_WALLETS,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [AdminRole.VIEW_ONLY]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_KYC_REQUESTS,
    PERMISSIONS.VIEW_CONFIG,
    PERMISSIONS.VIEW_SUPPORT_TICKETS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_WALLETS,
    PERMISSIONS.VIEW_AML_ALERTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
};

